import type { Metadata } from "next";
import "./globals.css";
import { Be_Vietnam_Pro } from "next/font/google";
import { ThemeProvider } from "@/components/custom/theme.provider";
// import PlayerComp from "@/components/custom/player.comp";
const myfont = Be_Vietnam_Pro({ 
  subsets: ["vietnamese"],
  weight: ["400", "600", "300"]
});

export const metadata: Metadata = {
  title: "Moozox",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={myfont.className}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          disableTransitionOnChange
        >
          {children}
          {/* <PlayerComp /> */}
        </ThemeProvider>
      </body>
    </html>
  );
}
